---
agof:
  #cac_repo: https://github.com/validatedpatterns-demos/agof_null_config
  cac_repo: git@github.com:mhjacks/agof_test_creds.git
  cac_revision: main

  agof_repo: https://github.com/mhjacks/agof.git
  agof_revision: aap_27_prep
