---
agof:
  extraPlaybookOpts: '-vvv'

  agof_repo: https://github.com/validatedpatterns/agof.git
  agof_revision: v2

  iac_repo: https://github.com/validatedpatterns-demos/agof_null_config
  iac_revision: main
