---
agof:
  iac_repo: https://github.com/validatedpatterns-demos/agof_null_config
  iac_revision: main

  agof_repo: https://github.com/mhjacks/agof
  agof_revision: skip_vault_magic
  extraPlaybookOpts: '-vvv'
